!=====================================================================!
! DERIVATIVE ACTION TOWER . LEVEL 6 . DERIVATIVE STRUCTURE
!
! The Gate-A load-bearing level. It answers one question: BEFORE
! DIFFERENTIATING ANYTHING NUMERICALLY, WHICH INDEPENDENT INPUTS
! CAN STRUCTURALLY INFLUENCE THE RESPONSE. Everything is derived
! from T_flow; nothing new is architect-owned here - the response
!
!      Z = { z }  c-->  C  c-->  V
!
! is already a value slot, so NO location relation is needed: where
! Learning required a residual-row carrier Y plus L = {(r,e)}
! because residual rows were not value slots, the derivative
! specimen's output is a subdomain, directly. That difference is
! architectural evidence, not an omission.
!
! The direct value dependency A_V = Q o I holds exactly four pairs,
!
!      (x,u)  (y,u)  (u,z)  (y,z)
!
! and carries the specimen's reason for existing: y reaches z along
! TWO structural routes - directly, and through u - while x reaches
! z only transitively, (x,z) absent yet reachable. The structural
! Jacobian pattern
!
!      J_ZX = { (z,x), (z,y) }
!
! is GENERATED by scanning response against inputs over the
! interpreted dependency, and its reverse J_XZ is transpose_of, a
! borrowing view of the same stored truth - never a second pattern,
! never a backprop graph.
!
! And the observation this rung exists to pin: SUPPORT IS NOT
! MULTIPLICITY. J_ZX holds (z,y) ONCE while the computation
! influences z through y twice. Jacobian sparsity says WHO matters;
! the evaluation structure says WHY and HOW OFTEN. Numerical
! reverse accumulation - a later gate's business - must therefore
! operate over the computational dependency structure, not merely
! scan the final J-pattern. No dz/dx, no dz/dy, no seed, no chain
! rule, no accumulation exists here: this is structure only.
!
! Author: Komahan Boopathy (komahan@gatech.edu)
!=====================================================================!

program derivative_level_6

  use derivative_assert, only : report, verdict
  use derivative_assert, only : SLOT_X, SLOT_Y, SLOT_U, SLOT_Z
  use derivative_assert, only : OP_PRODUCT, OP_SUM
  use derivative_assert, only : PORT_IN1, PORT_IN2, PORT_OUT
  use graph_fractal        , only : set_graph => graph
  use map_set_representation, only : counted_set_representation, &
       & listed_set_representation
  use map_set        , only : set_map
  use map_inclusion  , only : inclusion_map, declared_subobject
  use relation_finitary   , only : stored_relation, relation
  use relation_algebra, only : restrict_slot, project_slots, &
       &                             compose_binary
  use relation_binary , only : csr_relation, transposed_view, &
       &                             transpose_of
  use graph_algorithms , only : reachable
  use graph_fractal        , only : graph, known_branch, null_branch
  use graph_relational_view, only : relational_binding, &
       & num_member_sets, member_set_at, num_relations, relation_at, &
       & holds_set

  implicit none


  type(set_graph)              :: v, o, p
  type(set_graph)               :: x_dom, c, z, p_in, p_out
  type(stored_relation)          :: flow, backwards
  type(stored_relation)          :: consumes, produces
  type(csr_relation)             :: a, a2
  type(csr_relation), target     :: j_zx, j_zx2
  type(transposed_view)          :: jt, jt2
  type(graph)             , target :: g_a
  type(graph)             , target :: scell(1), selem(1)
  type(graph)             , target :: rcell(1), relem(1)
  type(relational_binding)         :: bnd
  integer                          :: kcell
  type(graph)             , target :: g_a2
  type(graph)             , target :: scell2(1), selem2(1)
  type(graph)             , target :: rcell2(1), relem2(1)
  type(relational_binding)         :: bnd2
  integer                          :: kcell2
  integer                        :: table(3, 6)
  integer                        :: nfail
  type(set_map)     :: sets
  type(inclusion_map)     :: inclusions

  nfail = 0

  write(*,'(1x,a)') "============================================="
  write(*,'(1x,a)') "derivative action tower . level 6 . structure"
  write(*,'(1x,a)') "============================================="

  call v % declare()
  call sets % bind(v, counted_set_representation(4))
  call o % declare()
  call sets % bind(o, counted_set_representation(2))
  call p % declare()
  call sets % bind(p, counted_set_representation(3))

  call x_dom % declare()
  call sets       % bind(x_dom, listed_set_representation([SLOT_Y, SLOT_X]))
  call inclusions % include_in(x_dom, v)
  call c % declare()
  call sets       % bind(c, listed_set_representation([SLOT_U, SLOT_Z]))
  call inclusions % include_in(c, v)
  call z % declare()
  call sets       % bind(z, listed_set_representation([SLOT_Z]))
  call inclusions % include_in(z, c)

  table(:, 1) = [OP_PRODUCT, SLOT_X, PORT_IN1]
  table(:, 2) = [OP_PRODUCT, SLOT_Y, PORT_IN2]
  table(:, 3) = [OP_PRODUCT, SLOT_U, PORT_OUT]
  table(:, 4) = [OP_SUM    , SLOT_U, PORT_IN1]
  table(:, 5) = [OP_SUM    , SLOT_Y, PORT_IN2]
  table(:, 6) = [OP_SUM    , SLOT_Z, PORT_OUT]
  flow = stored_relation('flow', [o, v, p], table, sets)

  call p_in % declare()
  call sets       % bind(p_in, listed_set_representation([PORT_IN1, PORT_IN2]))
  call inclusions % include_in(p_in, p)
  call p_out % declare()
  call sets       % bind(p_out, listed_set_representation([PORT_OUT]))
  call inclusions % include_in(p_out, p)

  a = derive_direct(flow)
  ! 'value dependency': (S, P) as one sequence on each branch.
  call g_a % declare()
  do kcell = 1, 1
     call scell(kcell) % declare()
     call selem(kcell) % declare()
  end do
  do kcell = 1, 1
     call rcell(kcell) % declare()
     call relem(kcell) % declare()
  end do

  call bnd % bind_set(selem(1), v)
  call bnd % bind_relation(relem(1), a)

  do kcell = 1, 1
     scell(kcell) % branch(1) = known_branch(selem(kcell))
     if (kcell .lt. 1) scell(kcell) % branch(2) = &
          & known_branch(scell(kcell + 1))
  end do
  do kcell = 1, 1
     rcell(kcell) % branch(1) = known_branch(relem(kcell))
     if (kcell .lt. 1) rcell(kcell) % branch(2) = &
          & known_branch(rcell(kcell + 1))
  end do

  g_a % branch(1) = known_branch(scell(1))
  g_a % branch(2) = known_branch(rcell(1))

  j_zx = derive_jacobian(a)

  call check_response_domain(nfail)
  call check_participation(nfail)
  call check_direct_dependency(nfail)
  call check_two_path_truth(nfail)
  call check_jacobian(nfail)
  call check_support_is_not_multiplicity(nfail)
  call check_reverse_is_the_view(nfail)
  call check_order_invariance(nfail)

  call verdict(nfail, "level 6")

contains

  !===================================================================!
  ! The direct value dependency, algebra end to end: I who-consumes,
  ! Q who-produces, A_V = Q o I - Level 2's own projections,
  ! composed in the other order.
  !===================================================================!

  function derive_direct(t_flow) result(dep)

    type(stored_relation), intent(in) :: t_flow
    type(csr_relation)                :: dep

    type(stored_relation) :: cons, prod

    cons = project_slots(restrict_slot(t_flow, 3, p_in , sets, inclusions), [2, 1], sets)
    prod = project_slots(restrict_slot(t_flow, 3, p_out, sets, inclusions), [1, 2], sets)
    dep  = compose_binary(cons, prod, sets)

    ! keep the participations visible for their own checks
    consumes = cons
    produces = prod

  end function derive_direct

  !===================================================================!
  ! The structural Jacobian pattern, generated - never written:
  ! (z_i, x_j) enters IFF input x_j reaches response z_i through the
  ! interpreted value dependency. The expected pairs may appear in
  ! assertions only.
  !===================================================================!

  function derive_jacobian(dv) result(jac)

    type(csr_relation), intent(in) :: dv
    type(csr_relation)                        :: jac

    integer, allocatable :: pairs(:,:)
    integer :: npairs, zi, xi

    allocate(pairs(2, sets % size_of(z) * sets % size_of(x_dom)))

    npairs = 0
    do zi = 1, sets % size_of(z)
       do xi = 1, sets % size_of(x_dom)
          if (reachable(dv, sets, sets % member_of(x_dom, xi), &
               &        sets % member_of(z, zi))) then
             npairs = npairs + 1
             pairs(:, npairs) = [sets % member_of(z, zi), sets % member_of(x_dom, xi)]
          end if
       end do
    end do

    jac = csr_relation('structural jacobian', z, x_dom, &
         & pairs(:, 1:npairs), sets)

  end function derive_jacobian

  !===================================================================!
  ! The response is a subdomain of the computed slots - and through
  ! them, of the value slots. NO residual-row carrier, NO location
  ! relation: where Learning needed Y and L because residual rows
  ! were not value slots, the derivative response already IS one.
  !===================================================================!

  subroutine check_response_domain(nfail)

    integer, intent(inout) :: nfail

    call report(sets % size_of(z) .eq. 1 .and. sets % has_in(z, SLOT_Z) .and. &
         &      .not. sets % has_in(z, SLOT_U), &
         & "Z = { z }, the response", nfail)
    call report(declared_subobject(z, c, inclusions) .and. declared_subobject(z, v, inclusions), &
         & "embedded in the computed slots, and through them in V - " // &
         & "no location relation needed", nfail)

  end subroutine check_response_domain

  !===================================================================!
  ! Input and output participation, exact - restricted and projected
  ! out of the flow, nothing hand-written.
  !===================================================================!

  subroutine check_participation(nfail)

    integer, intent(inout) :: nfail

    type(set_graph) :: dom

    dom = consumes % domain(1)
    call report(dom % same_as(v), "I runs from the value slots", nfail)
    dom = consumes % domain(2)
    call report(dom % same_as(o), "into the operations", nfail)
    call report(consumes % num_tuples() .eq. 4 .and. &
         &      consumes % has([SLOT_X, OP_PRODUCT]) .and. &
         &      consumes % has([SLOT_Y, OP_PRODUCT]) .and. &
         &      consumes % has([SLOT_U, OP_SUM    ]) .and. &
         &      consumes % has([SLOT_Y, OP_SUM    ]), &
         & "I = { (x,product), (y,product), (u,sum), (y,sum) } " // &
         & "- exactly", nfail)

    dom = produces % domain(1)
    call report(dom % same_as(o), "Q runs from the operations", nfail)
    dom = produces % domain(2)
    call report(dom % same_as(v), "back into the value slots", nfail)
    call report(produces % num_tuples() .eq. 2 .and. &
         &      produces % has([OP_PRODUCT, SLOT_U]) .and. &
         &      produces % has([OP_SUM    , SLOT_Z]), &
         & "Q = { (product,u), (sum,z) } - exactly", nfail)

  end subroutine check_participation

  !===================================================================!
  ! The composed dependency: four direct pairs, and the absences
  ! that make transitivity mean something.
  !===================================================================!

  subroutine check_direct_dependency(nfail)

    integer, intent(inout) :: nfail

    type(set_graph) :: dom

    dom = a % domain(1)
    call report(dom % same_as(v), "A_V runs from the value slots", nfail)
    dom = a % domain(2)
    call report(dom % same_as(v), "back into the value slots", nfail)

    call report(a % num_tuples() .eq. 4 .and. &
         &      a % has([SLOT_X, SLOT_U]) .and. &
         &      a % has([SLOT_Y, SLOT_U]) .and. &
         &      a % has([SLOT_U, SLOT_Z]) .and. &
         &      a % has([SLOT_Y, SLOT_Z]), &
         & "A_V = { (x,u), (y,u), (u,z), (y,z) } - exactly", nfail)
    call report(.not. a % has([SLOT_X, SLOT_Z]) .and. &
         &      .not. a % has([SLOT_Z, SLOT_X]), &
         & "x touches z in neither direction: influence is not " // &
         & "adjacency", nfail)

  end subroutine check_direct_dependency

  !===================================================================!
  ! The two-path truth, the specimen's reason for existing: y
  ! reaches z directly AND through u; x reaches z only through u.
  ! This is the topology future reverse accumulation must respect.
  !===================================================================!

  subroutine check_two_path_truth(nfail)

    integer, intent(inout) :: nfail

    call report(a % has([SLOT_Y, SLOT_Z]), &
         & "y -> z is a DIRECT dependency", nfail)
    call report(a % has([SLOT_Y, SLOT_U]) .and. &
         &      a % has([SLOT_U, SLOT_Z]), &
         & "and y -> u -> z stands beside it: two routes to one " // &
         & "response", nfail)
    call report(.not. a % has([SLOT_X, SLOT_Z]) .and. &
         &      reachable(a, sets, SLOT_X, SLOT_Z), &
         & "x -> u -> z: transitive only, hard-coded never", nfail)
    call report(.not. reachable(a, sets, SLOT_Z, SLOT_X) .and. &
         &      .not. reachable(a, sets, SLOT_Z, SLOT_Y), &
         & "nothing flows back out of the response", nfail)

  end subroutine check_two_path_truth

  !===================================================================!
  ! J_ZX, exact: both inputs reach the one response, so both pairs
  ! stand - derived by the scan, named only here.
  !===================================================================!

  subroutine check_jacobian(nfail)

    integer, intent(inout) :: nfail

    type(set_graph) :: dom

    dom = j_zx % domain(1)
    call report(dom % same_as(z), &
         & "J_ZX runs from the response", nfail)
    dom = j_zx % domain(2)
    call report(dom % same_as(x_dom), &
         & "into the independent inputs", nfail)

    call report(j_zx % num_tuples() .eq. 2 .and. &
         &      j_zx % has([SLOT_Z, SLOT_X]) .and. &
         &      j_zx % has([SLOT_Z, SLOT_Y]), &
         & "J_ZX = { (z,x), (z,y) }: both inputs structurally " // &
         & "matter", nfail)

  end subroutine check_jacobian

  !===================================================================!
  ! THE Gate-A observation: support is not multiplicity. J_ZX holds
  ! (z,y) ONCE - a relation is a set - while the value dependency
  ! holds BOTH routes by which y influences z. Sparsity says WHO;
  ! the evaluation structure says HOW OFTEN. Reverse accumulation,
  ! when a later gate earns it, must walk the finer structure.
  !===================================================================!

  subroutine check_support_is_not_multiplicity(nfail)

    integer, intent(inout) :: nfail

    call report(j_zx % num_tuples() .eq. 2 .and. &
         &      j_zx % has([SLOT_Z, SLOT_Y]), &
         & "the pattern holds (z,y) once: a relation is a set", nfail)
    call report(a % has([SLOT_Y, SLOT_Z]) .and. &
         &      a % has([SLOT_Y, SLOT_U]) .and. &
         &      a % has([SLOT_U, SLOT_Z]), &
         & "while the computation holds two y-routes: support is " // &
         & "not multiplicity", nfail)

  end subroutine check_support_is_not_multiplicity

  !===================================================================!
  ! One dependency description: the reverse structure is the
  ! transpose VIEW of J_ZX - borrowed, never a second stored
  ! pattern, never a backprop graph.
  !===================================================================!

  subroutine check_reverse_is_the_view(nfail)

    integer, intent(inout) :: nfail

    jt = transpose_of(j_zx)

    call report(jt % num_tuples() .eq. 2 .and. &
         &      jt % has([SLOT_X, SLOT_Z]) .and. &
         &      jt % has([SLOT_Y, SLOT_Z]), &
         & "J_XZ = { (x,z), (y,z) }: the same truth, ends swapped", &
         & nfail)
    call report(j_zx % materialized() .and. &
         &      .not. jt % materialized(), &
         & "the forward is materialized; the reverse merely borrows", &
         & nfail)

  end subroutine check_reverse_is_the_view

  !===================================================================!
  ! The six facts handed backwards derive the same A_V, the same
  ! J_ZX and the same reverse view - equal as sets, both directions:
  ! the structure belongs to the specimen, not to how its table was
  ! typed.
  !===================================================================!

  subroutine check_order_invariance(nfail)

    integer, intent(inout) :: nfail

    integer              :: rev(3, 6), k
    integer, allocatable :: t1(:,:), t2(:,:)
    logical              :: ok

    do k = 1, 6
       rev(:, k) = table(:, 7 - k)
    end do
    backwards = stored_relation('flow backwards', [o, v, p], rev, sets)

    a2 = derive_direct(backwards)
    ! 'value dependency again': (S, P) as one sequence on each branch.
    call g_a2 % declare()
    do kcell2 = 1, 1
       call scell2(kcell2) % declare()
       call selem2(kcell2) % declare()
    end do
    do kcell2 = 1, 1
       call rcell2(kcell2) % declare()
       call relem2(kcell2) % declare()
    end do

    call bnd2 % bind_set(selem2(1), v)
    call bnd2 % bind_relation(relem2(1), a2)

    do kcell2 = 1, 1
       scell2(kcell2) % branch(1) = known_branch(selem2(kcell2))
       if (kcell2 .lt. 1) scell2(kcell2) % branch(2) = &
            & known_branch(scell2(kcell2 + 1))
    end do
    do kcell2 = 1, 1
       rcell2(kcell2) % branch(1) = known_branch(relem2(kcell2))
       if (kcell2 .lt. 1) rcell2(kcell2) % branch(2) = &
            & known_branch(rcell2(kcell2 + 1))
    end do

    g_a2 % branch(1) = known_branch(scell2(1))
    g_a2 % branch(2) = known_branch(rcell2(1))
    j_zx2 = derive_jacobian(a2)
    jt2 = transpose_of(j_zx2)

    call report(a2 % num_tuples() .eq. a % num_tuples(), &
         & "|A1| = |A2|", nfail)
    call a % tuples(t1)
    call a2 % tuples(t2)
    ok = .true.
    do k = 1, size(t1, 2)
       ok = ok .and. a2 % has(t1(:, k))
    end do
    do k = 1, size(t2, 2)
       ok = ok .and. a % has(t2(:, k))
    end do
    call report(ok, &
         & "each A holds every pair of the other: equal as sets", &
         & nfail)

    call report(j_zx2 % num_tuples() .eq. j_zx % num_tuples(), &
         & "|J1| = |J2|", nfail)
    call j_zx % tuples(t1)
    call j_zx2 % tuples(t2)
    ok = .true.
    do k = 1, size(t1, 2)
       ok = ok .and. j_zx2 % has(t1(:, k))
    end do
    do k = 1, size(t2, 2)
       ok = ok .and. j_zx % has(t2(:, k))
    end do
    call report(ok, &
         & "and so are the Jacobian patterns, both directions", nfail)

    call report(jt2 % num_tuples() .eq. 2 .and. &
         &      jt2 % has([SLOT_X, SLOT_Z]) .and. &
         &      jt2 % has([SLOT_Y, SLOT_Z]), &
         & "and the reverse view answers identically either way", &
         & nfail)

  end subroutine check_order_invariance

end program derivative_level_6
