!=====================================================================!
! DERIVATIVE ACTION TOWER . LEVEL 6 . DERIVATIVE STRUCTURE
!
! The Gate-A load-bearing level. It answers one question: BEFORE
! DIFFERENTIATING ANYTHING NUMERICALLY, WHICH INDEPENDENT INPUTS
! CAN STRUCTURALLY INFLUENCE THE RESPONSE. Everything is derived
! from R_flow; nothing new is architect-owned here - the response
!
!      Z = { z }  c-->  C  c-->  V
!
! is already a value slot, so NO location relation is needed: where
! Learning required a residual-row carrier Y plus L = {(r,e)}
! because residual rows were not value slots, the derivative
! specimen's output is a subdomain, directly. That difference is
! architectural evidence, not an omission.
!
! The direct value dependency A_V = Q o I holds exactly four pairs,
!
!      (x,u)  (y,u)  (u,z)  (y,z)
!
! and carries the specimen's reason for existing: y reaches z along
! TWO structural routes - directly, and through u - while x reaches
! z only transitively, (x,z) absent yet reachable. The structural
! Jacobian pattern
!
!      J_ZX = { (z,x), (z,y) }
!
! is GENERATED by scanning response against inputs over the
! interpreted dependency, and its reverse J_XZ is transpose_of, a
! borrowing view of the same stored truth - never a second pattern,
! never a backprop graph.
!
! And the observation this rung exists to pin: SUPPORT IS NOT
! MULTIPLICITY. J_ZX holds (z,y) ONCE while the computation
! influences z through y twice. Jacobian sparsity says WHO matters;
! the evaluation structure says WHY and HOW OFTEN. Numerical
! reverse accumulation - a later gate's business - must therefore
! operate over the computational dependency structure, not merely
! scan the final J-pattern. No dz/dx, no dz/dy, no seed, no chain
! rule, no accumulation exists here: this is structure only.
!
! Author: Komahan Boopathy (komahan@gatech.edu)
!=====================================================================!

program derivative_level_6

  use derivative_assert, only : report, verdict
  use derivative_assert, only : SLOT_X, SLOT_Y, SLOT_U, SLOT_Z
  use derivative_assert, only : OP_PRODUCT, OP_SUM
  use derivative_assert, only : PORT_IN1, PORT_IN2, PORT_OUT
  use graph_carrier    , only : counted_set, subset_set, member_set
  use graph_relation   , only : stored_relation, relation
  use graph_relation_algebra, only : restrict_slot, project_slots, &
       &                             compose_binary
  use graph_binary_relation , only : csr_relation, transposed_view, &
       &                             transpose_of
  use graph_structure  , only : relational_graph, held_set, held_relation
  use graph_profile    , only : directed_adjacency_view
  use graph_algorithms , only : reachable

  implicit none

  type(counted_set)              :: v, o, p
  type(subset_set)               :: x_dom, c, z, p_in, p_out
  type(stored_relation)          :: flow, backwards
  type(stored_relation)          :: consumes, produces
  type(csr_relation)             :: a, a2
  type(csr_relation), target     :: j_zx, j_zx2
  type(transposed_view)          :: jt, jt2
  type(relational_graph), target :: g_a, g_a2
  type(directed_adjacency_view)  :: dep_view, dep_view2
  integer                        :: table(3, 6)
  integer                        :: nfail

  nfail = 0

  write(*,'(1x,a)') "============================================="
  write(*,'(1x,a)') "derivative action tower . level 6 . structure"
  write(*,'(1x,a)') "============================================="

  v = counted_set('value-slots', 4)
  o = counted_set('operations' , 2)
  p = counted_set('ports'      , 3)

  x_dom = subset_set('independent', v, [SLOT_Y, SLOT_X])
  c     = subset_set('computed'   , v, [SLOT_U, SLOT_Z])
  z     = subset_set('response'   , c, [SLOT_Z])

  table(:, 1) = [OP_PRODUCT, SLOT_X, PORT_IN1]
  table(:, 2) = [OP_PRODUCT, SLOT_Y, PORT_IN2]
  table(:, 3) = [OP_PRODUCT, SLOT_U, PORT_OUT]
  table(:, 4) = [OP_SUM    , SLOT_U, PORT_IN1]
  table(:, 5) = [OP_SUM    , SLOT_Y, PORT_IN2]
  table(:, 6) = [OP_SUM    , SLOT_Z, PORT_OUT]
  flow = stored_relation('flow', [o, v, p], table)

  p_in  = subset_set('input-ports', p, [PORT_IN1, PORT_IN2])
  p_out = subset_set('output-port', p, [PORT_OUT])

  a = derive_direct(flow)
  g_a = relational_graph('value dependency', [held_set(v)], &
       & [held_relation(a)])
  dep_view = directed_adjacency_view(g_a, a)

  j_zx = derive_jacobian(dep_view)

  call check_response_domain(nfail)
  call check_participation(nfail)
  call check_direct_dependency(nfail)
  call check_two_path_truth(nfail)
  call check_jacobian(nfail)
  call check_support_is_not_multiplicity(nfail)
  call check_reverse_is_the_view(nfail)
  call check_order_invariance(nfail)

  call verdict(nfail, "level 6")

contains

  !===================================================================!
  ! The direct value dependency, algebra end to end: I who-consumes,
  ! Q who-produces, A_V = Q o I - Level 2's own projections,
  ! composed in the other order.
  !===================================================================!

  function derive_direct(r_flow) result(dep)

    type(stored_relation), intent(in) :: r_flow
    type(csr_relation)                :: dep

    type(stored_relation) :: cons, prod

    cons = project_slots(restrict_slot(r_flow, 3, p_in ), [2, 1])
    prod = project_slots(restrict_slot(r_flow, 3, p_out), [1, 2])
    dep  = compose_binary(cons, prod)

    ! keep the participations visible for their own checks
    consumes = cons
    produces = prod

  end function derive_direct

  !===================================================================!
  ! The structural Jacobian pattern, generated - never written:
  ! (z_i, x_j) enters IFF input x_j reaches response z_i through the
  ! interpreted value dependency. The expected pairs may appear in
  ! assertions only.
  !===================================================================!

  function derive_jacobian(dv) result(jac)

    type(directed_adjacency_view), intent(in) :: dv
    type(csr_relation)                        :: jac

    integer :: pairs(2, z % size() * x_dom % size())
    integer :: npairs, zi, xi

    npairs = 0
    do zi = 1, z % size()
       do xi = 1, x_dom % size()
          if (reachable(dv, x_dom % member(xi), z % member(zi))) then
             npairs = npairs + 1
             pairs(:, npairs) = [z % member(zi), x_dom % member(xi)]
          end if
       end do
    end do

    jac = csr_relation('structural jacobian', z, x_dom, &
         & pairs(:, 1:npairs))

  end function derive_jacobian

  !===================================================================!
  ! The response is a subdomain of the computed slots - and through
  ! them, of the value slots. NO residual-row carrier, NO location
  ! relation: where Learning needed Y and L because residual rows
  ! were not value slots, the derivative response already IS one.
  !===================================================================!

  subroutine check_response_domain(nfail)

    integer, intent(inout) :: nfail

    call report(z % size() .eq. 1 .and. z % has(SLOT_Z) .and. &
         &      .not. z % has(SLOT_U), &
         & "Z = { z }, the response", nfail)
    call report(z % is_subobject_of(c) .and. z % is_subobject_of(v), &
         & "embedded in the computed slots, and through them in V - " // &
         & "no location relation needed", nfail)

  end subroutine check_response_domain

  !===================================================================!
  ! Input and output participation, exact - restricted and projected
  ! out of the flow, nothing hand-written.
  !===================================================================!

  subroutine check_participation(nfail)

    integer, intent(inout) :: nfail

    class(member_set), allocatable :: dom

    dom = consumes % domain(1)
    call report(dom % same_as(v), "I runs from the value slots", nfail)
    dom = consumes % domain(2)
    call report(dom % same_as(o), "into the operations", nfail)
    call report(consumes % num_tuples() .eq. 4 .and. &
         &      consumes % has([SLOT_X, OP_PRODUCT]) .and. &
         &      consumes % has([SLOT_Y, OP_PRODUCT]) .and. &
         &      consumes % has([SLOT_U, OP_SUM    ]) .and. &
         &      consumes % has([SLOT_Y, OP_SUM    ]), &
         & "I = { (x,product), (y,product), (u,sum), (y,sum) } " // &
         & "- exactly", nfail)

    dom = produces % domain(1)
    call report(dom % same_as(o), "Q runs from the operations", nfail)
    dom = produces % domain(2)
    call report(dom % same_as(v), "back into the value slots", nfail)
    call report(produces % num_tuples() .eq. 2 .and. &
         &      produces % has([OP_PRODUCT, SLOT_U]) .and. &
         &      produces % has([OP_SUM    , SLOT_Z]), &
         & "Q = { (product,u), (sum,z) } - exactly", nfail)

  end subroutine check_participation

  !===================================================================!
  ! The composed dependency: four direct pairs, and the absences
  ! that make transitivity mean something.
  !===================================================================!

  subroutine check_direct_dependency(nfail)

    integer, intent(inout) :: nfail

    class(member_set), allocatable :: dom

    dom = a % domain(1)
    call report(dom % same_as(v), "A_V runs from the value slots", nfail)
    dom = a % domain(2)
    call report(dom % same_as(v), "back into the value slots", nfail)

    call report(a % num_tuples() .eq. 4 .and. &
         &      a % has([SLOT_X, SLOT_U]) .and. &
         &      a % has([SLOT_Y, SLOT_U]) .and. &
         &      a % has([SLOT_U, SLOT_Z]) .and. &
         &      a % has([SLOT_Y, SLOT_Z]), &
         & "A_V = { (x,u), (y,u), (u,z), (y,z) } - exactly", nfail)
    call report(.not. a % has([SLOT_X, SLOT_Z]) .and. &
         &      .not. a % has([SLOT_Z, SLOT_X]), &
         & "x touches z in neither direction: influence is not " // &
         & "adjacency", nfail)

  end subroutine check_direct_dependency

  !===================================================================!
  ! The two-path truth, the specimen's reason for existing: y
  ! reaches z directly AND through u; x reaches z only through u.
  ! This is the topology future reverse accumulation must respect.
  !===================================================================!

  subroutine check_two_path_truth(nfail)

    integer, intent(inout) :: nfail

    call report(a % has([SLOT_Y, SLOT_Z]), &
         & "y -> z is a DIRECT dependency", nfail)
    call report(a % has([SLOT_Y, SLOT_U]) .and. &
         &      a % has([SLOT_U, SLOT_Z]), &
         & "and y -> u -> z stands beside it: two routes to one " // &
         & "response", nfail)
    call report(.not. a % has([SLOT_X, SLOT_Z]) .and. &
         &      reachable(dep_view, SLOT_X, SLOT_Z), &
         & "x -> u -> z: transitive only, hard-coded never", nfail)
    call report(.not. reachable(dep_view, SLOT_Z, SLOT_X) .and. &
         &      .not. reachable(dep_view, SLOT_Z, SLOT_Y), &
         & "nothing flows back out of the response", nfail)

  end subroutine check_two_path_truth

  !===================================================================!
  ! J_ZX, exact: both inputs reach the one response, so both pairs
  ! stand - derived by the scan, named only here.
  !===================================================================!

  subroutine check_jacobian(nfail)

    integer, intent(inout) :: nfail

    class(member_set), allocatable :: dom

    dom = j_zx % domain(1)
    call report(dom % same_as(z), &
         & "J_ZX runs from the response", nfail)
    dom = j_zx % domain(2)
    call report(dom % same_as(x_dom), &
         & "into the independent inputs", nfail)

    call report(j_zx % num_tuples() .eq. 2 .and. &
         &      j_zx % has([SLOT_Z, SLOT_X]) .and. &
         &      j_zx % has([SLOT_Z, SLOT_Y]), &
         & "J_ZX = { (z,x), (z,y) }: both inputs structurally " // &
         & "matter", nfail)

  end subroutine check_jacobian

  !===================================================================!
  ! THE Gate-A observation: support is not multiplicity. J_ZX holds
  ! (z,y) ONCE - a relation is a set - while the value dependency
  ! holds BOTH routes by which y influences z. Sparsity says WHO;
  ! the evaluation structure says HOW OFTEN. Reverse accumulation,
  ! when a later gate earns it, must walk the finer structure.
  !===================================================================!

  subroutine check_support_is_not_multiplicity(nfail)

    integer, intent(inout) :: nfail

    call report(j_zx % num_tuples() .eq. 2 .and. &
         &      j_zx % has([SLOT_Z, SLOT_Y]), &
         & "the pattern holds (z,y) once: a relation is a set", nfail)
    call report(a % has([SLOT_Y, SLOT_Z]) .and. &
         &      a % has([SLOT_Y, SLOT_U]) .and. &
         &      a % has([SLOT_U, SLOT_Z]), &
         & "while the computation holds two y-routes: support is " // &
         & "not multiplicity", nfail)

  end subroutine check_support_is_not_multiplicity

  !===================================================================!
  ! One dependency description: the reverse structure is the
  ! transpose VIEW of J_ZX - borrowed, never a second stored
  ! pattern, never a backprop graph.
  !===================================================================!

  subroutine check_reverse_is_the_view(nfail)

    integer, intent(inout) :: nfail

    jt = transpose_of(j_zx)

    call report(jt % num_tuples() .eq. 2 .and. &
         &      jt % has([SLOT_X, SLOT_Z]) .and. &
         &      jt % has([SLOT_Y, SLOT_Z]), &
         & "J_XZ = { (x,z), (y,z) }: the same truth, ends swapped", &
         & nfail)
    call report(j_zx % materialized() .and. &
         &      .not. jt % materialized(), &
         & "the forward is materialized; the reverse merely borrows", &
         & nfail)

  end subroutine check_reverse_is_the_view

  !===================================================================!
  ! The six facts handed backwards derive the same A_V, the same
  ! J_ZX and the same reverse view - equal as sets, both directions:
  ! the structure belongs to the specimen, not to how its table was
  ! typed.
  !===================================================================!

  subroutine check_order_invariance(nfail)

    integer, intent(inout) :: nfail

    integer              :: rev(3, 6), k
    integer, allocatable :: t1(:,:), t2(:,:)
    logical              :: ok

    do k = 1, 6
       rev(:, k) = table(:, 7 - k)
    end do
    backwards = stored_relation('flow backwards', [o, v, p], rev)

    a2 = derive_direct(backwards)
    g_a2 = relational_graph('value dependency again', [held_set(v)], &
         & [held_relation(a2)])
    dep_view2 = directed_adjacency_view(g_a2, a2)
    j_zx2 = derive_jacobian(dep_view2)
    jt2 = transpose_of(j_zx2)

    call report(a2 % num_tuples() .eq. a % num_tuples(), &
         & "|A1| = |A2|", nfail)
    call a % tuples(t1)
    call a2 % tuples(t2)
    ok = .true.
    do k = 1, size(t1, 2)
       ok = ok .and. a2 % has(t1(:, k))
    end do
    do k = 1, size(t2, 2)
       ok = ok .and. a % has(t2(:, k))
    end do
    call report(ok, &
         & "each A holds every pair of the other: equal as sets", &
         & nfail)

    call report(j_zx2 % num_tuples() .eq. j_zx % num_tuples(), &
         & "|J1| = |J2|", nfail)
    call j_zx % tuples(t1)
    call j_zx2 % tuples(t2)
    ok = .true.
    do k = 1, size(t1, 2)
       ok = ok .and. j_zx2 % has(t1(:, k))
    end do
    do k = 1, size(t2, 2)
       ok = ok .and. j_zx % has(t2(:, k))
    end do
    call report(ok, &
         & "and so are the Jacobian patterns, both directions", nfail)

    call report(jt2 % num_tuples() .eq. 2 .and. &
         &      jt2 % has([SLOT_X, SLOT_Z]) .and. &
         &      jt2 % has([SLOT_Y, SLOT_Z]), &
         & "and the reverse view answers identically either way", &
         & nfail)

  end subroutine check_order_invariance

end program derivative_level_6
