!=====================================================================!
! Restarted GMRES on the tower.
!
! For any operator, symmetric or not: build an orthonormal basis of
! the Krylov directions generated by the operator, and take the
! minimising solution that basis can express,
!
!      minimise || rhs - A x ||   over   x0 + span{r, Ar, A^2 r, ...}
!
! The basis grows one matvec at a time (Arnoldi, with the inner
! product keeping it orthonormal); a pair of rotations keeps the
! small problem triangular, so the residual norm is read without
! solving the small problem until the end. After `restart` directions
! the basis is discarded and the iteration restarts from the current
! iterate.
!
! Everything the solver needs is inherited: matvec, inner_product,
! norm. This file states the iteration and nothing else.
!
! A preconditioner, when stored, is a minimizer stated on the same
! operator and applied to every direction the operator produces, so
! the basis spans the Krylov directions of M^-1 A; the residual the
! restarts measure is the operator's own.
!
! Author: Komahan Boopathy (komahan@gatech.edu)
!=====================================================================!

module operation_gmres

  use util_precision  , only : dp
  use operation_minimization, only : minimizer, state, restrict, solve_result, SOLVE_BREAKDOWN, SOLVE_INNER_FAILED, SOLVE_STAGNATED
  use, intrinsic :: ieee_arithmetic, only : ieee_is_finite
  use util_tally, only : tally_record, linear_solves
  use view_directed, only : directed_graph
  use view_directed_stored, only : stored_directed_graph
  use graph_fractal, only : graph
  use operation_action, only : operation
  use field_stored, only : stored_field

  implicit none

  private
  public :: gmres

  type, extends(minimizer) :: gmres

     integer :: restart = 30
     class(minimizer), allocatable :: preconditioner

   contains

     procedure :: name => gmres_name
     procedure :: state => gmres_state
     procedure :: restrict => gmres_restrict
     procedure :: solve

  end type gmres

contains

  pure function gmres_name(this) result(name)

    class(gmres), intent(in) :: this
    character(len=:), allocatable :: name

    associate (u1 => this); end associate

    name = 'gmres'

  end function gmres_name


  !===================================================================!
  ! The operator stated on this solver and on its preconditioner.
  !===================================================================!

  subroutine gmres_state(this, action, context, unknown_domain, num_unknowns, &
       & num_components, coupling, stored_inputs)

    class(gmres)         , intent(inout) :: this
    class(operation)     , intent(in)    :: action
    class(directed_graph), intent(in)    :: context
    type(graph)          , intent(in)    :: unknown_domain
    integer              , intent(in)    :: num_unknowns
    integer              , intent(in), optional :: num_components
    class(directed_graph), intent(in), optional :: coupling
    type(stored_field)   , intent(in), optional :: stored_inputs(:)

    call state(this, action, context, unknown_domain, num_unknowns, &
         & num_components, coupling, stored_inputs)
    ! a blocked preconditioner is stated with the coupling of the
    ! blocks, the unknowns' coupling read through them
    if (allocated(this % preconditioner)) then
       if (this % preconditioner % block_width > 1) then
          if (present(coupling)) then
             call this % preconditioner % state(action, context, unknown_domain, num_unknowns, &
                  & num_components, blocked(coupling, this % preconditioner % block_width), stored_inputs)
          else
             call this % preconditioner % state(action, context, unknown_domain, num_unknowns, &
                  & num_components, blocked(context, this % preconditioner % block_width), stored_inputs)
          end if
       else
          call this % preconditioner % state(action, context, unknown_domain, num_unknowns, &
               & num_components, coupling, stored_inputs)
       end if
    end if

  end subroutine gmres_state

  !===================================================================!
  ! The preconditioner is stated on the same operator, so it is
  ! restricted by the selection itself.
  !===================================================================!

  subroutine gmres_restrict(this, selected)

    class(gmres), intent(inout) :: this
    integer     , intent(in)    :: selected(:)

    call restrict(this, selected)
    if (allocated(this % preconditioner)) call this % preconditioner % restrict(selected)

  end subroutine gmres_restrict

  !===================================================================!
  ! The coupling of the blocks of `width` consecutive unknowns: an
  ! edge between two blocks for every edge of the unknowns' coupling
  ! between them, none within a block.
  !===================================================================!

  function blocked(coupling, width) result(blocks)

    class(directed_graph), intent(in) :: coupling
    integer              , intent(in) :: width
    type(stored_directed_graph) :: blocks

    integer, allocatable :: tails(:), heads(:)
    integer :: e, ne, t, h, n

    ne = coupling % num_edges()
    allocate(tails(ne), heads(ne))
    n = 0
    do e = 1, ne
       if (.not. coupling % edge_has_head(e)) cycle
       t = (coupling % edge_tail(e) - 1) / width + 1
       h = (coupling % edge_head(e) - 1) / width + 1
       if (t == h) cycle
       n = n + 1
       tails(n) = t
       heads(n) = h
    end do
    blocks = stored_directed_graph(coupling % num_vertices() / width, tails=tails(1:n), heads=heads(1:n))

  end function blocked

  !===================================================================!
  ! The direction through the preconditioner: M^-1 v, or v itself
  ! when none is stored.
  !===================================================================!

  subroutine preconditioned(this, v, z, direction_admissible)

    class(gmres), intent(inout) :: this
    real(dp)    , intent(in)    :: v(:)
    real(dp), allocatable, intent(out) :: z(:)
    logical, intent(out) :: direction_admissible

    real(dp) :: reduced
    type(solve_result) :: outcome

    direction_admissible = .true.
    if (.not. allocated(this % preconditioner)) then
       z = v
       direction_admissible = all(ieee_is_finite(z))
       return
    end if
    allocate(z(size(v)), source=0.0_dp)
    call this % preconditioner % solve(v, z, reduced)
    outcome = this % preconditioner % result()
    direction_admissible = .not. outcome % failed() .and. ieee_is_finite(reduced) .and. all(ieee_is_finite(z))

  end subroutine preconditioned

  subroutine solve(this, rhs, x, achieved)

    class(gmres), intent(inout) :: this
    real(dp), intent(in)    :: rhs(:)
    real(dp), intent(inout) :: x(:)
    real(dp), intent(out)   :: achieved

    real(dp), allocatable :: basis(:,:), h(:,:), cs(:), sn(:), s(:)
    real(dp), allocatable :: r(:), w(:), y(:), z(:)
    real(dp) :: beta, hik, radius, subdiag, unpreconditioned
    integer :: n, m, outer, i, j, k
    logical :: direction_admissible, breakdown, invariant

    call tally_record(linear_solves)

    n = size(x)
    m = min(max(this % restart, 1), n)

    allocate(basis(n, m + 1), h(m + 1, m), cs(m), sn(m), s(m + 1))

    call this % initialize_residual_history()
    call this % imbalance(rhs, x, r)
    achieved = this % norm(r)
    if (this % terminated(achieved, 0)) return

    do outer = 1, this % max_iterations

       ! the basis begins from the preconditioned residual
       unpreconditioned = achieved
       call preconditioned(this, r, z, direction_admissible)
       if (.not. direction_admissible) then
          call this % record_result(achieved, outer - 1, SOLVE_INNER_FAILED)
          return
       end if
       beta = this % norm(z)
       if (.not. ieee_is_finite(beta)) then
          call this % record_result(achieved, outer - 1, SOLVE_INNER_FAILED)
          return
       end if
       if (beta <= tiny(1.0_dp)) then
          call this % record_result(achieved, outer - 1, SOLVE_BREAKDOWN)
          return
       end if
       basis = 0.0_dp
       h  = 0.0_dp
       s  = 0.0_dp
       s(1) = beta
       basis(:, 1) = z / beta
       breakdown = .false.
       invariant = .false.
       k = 0

       do j = 1, m

          ! One more direction from the operator, orthonormalised.
          ! The unrotated subdiagonal is retained separately: the
          ! rotations overwrite its entry, and both the next basis
          ! vector and the breakdown test need the unrotated value.
          call this % matvec(basis(:, j), z)
          call preconditioned(this, z, w, direction_admissible)
          if (.not. direction_admissible) then
             call this % record_result(unpreconditioned, outer - 1, SOLVE_INNER_FAILED)
             achieved = unpreconditioned
             return
          end if
          do i = 1, j
             h(i, j) = this % inner_product(w, basis(:, i))
             w = w - h(i, j) * basis(:, i)
          end do
          subdiag     = this % norm(w)
          h(j + 1, j) = subdiag
          invariant = subdiag <= tiny(1.0_dp) .or. j == n

          if (j < m .and. subdiag > tiny(1.0_dp)) then
             basis(:, j + 1) = w / subdiag
          end if

          ! The previous rotations, then the new one.
          do i = 1, j - 1
             hik        = cs(i) * h(i, j) + sn(i) * h(i + 1, j)
             h(i + 1, j) = -sn(i) * h(i, j) + cs(i) * h(i + 1, j)
             h(i, j)     = hik
          end do

          radius = hypot(h(j, j), h(j + 1, j))
          if (radius <= tiny(1.0_dp)) then
             k = j - 1
             breakdown = .true.
             exit
          end if
          cs(j) = h(j, j) / radius
          sn(j) = h(j + 1, j) / radius
          h(j, j)     = radius
          h(j + 1, j) = 0.0_dp

          s(j + 1) = -sn(j) * s(j)
          s(j)     =  cs(j) * s(j)

          k = j
          ! This estimate selects when to form a candidate. Scale its
          ! reduction by the true residual at the start of this restart;
          ! its acceptance below always measures rhs - A x directly.
          achieved = (abs(s(j + 1)) / beta) * unpreconditioned
          if (this % converged(achieved)) exit
          if (subdiag <= tiny(1.0_dp)) exit

       end do

       ! The minimising solution this basis can express.
       allocate(y(k))
       do i = k, 1, -1
          y(i) = s(i)
          do j = i + 1, k
             y(i) = y(i) - h(i, j) * y(j)
          end do
          y(i) = y(i) / h(i, i)
       end do
       do i = 1, k
          x = x + y(i) * basis(:, i)
       end do
       deallocate(y)

       call this % imbalance(rhs, x, r)
       achieved = this % norm(r)
       if (breakdown .and. .not. this % converged(achieved)) then
          call this % record_residual_norm(achieved)
          call this % record_result(achieved, outer, SOLVE_BREAKDOWN)
          return
       end if
       if (this % terminated(achieved, outer)) return
       ! An invariant Krylov space has no further direction to add.
       ! A discrepancy in its true residual (for example, a numerical
       ! directional difference) is reported as stagnation, not as a
       ! converged solve. An outer minimizer may use the finite step.
       if (invariant) then
          call this % record_result(achieved, outer, SOLVE_STAGNATED)
          return
       end if

    end do

  end subroutine solve

end module operation_gmres
