!=====================================================================!
! LEARNING TOWER . LEVEL 6 . DISCRETIZATION
!
! The level answers one question: WHICH TRAINABLE PARAMETERS CAN
! STRUCTURALLY INFLUENCE EACH TRAINING RESIDUAL. One genuinely new
! fact enters - the LOCATION relation,
!
!      L <= Y x V        L = { (r, e) }
!
! where Y = { r } is the residual row, born at this level and
! nowhere below. EVERYTHING ELSE IS DERIVED: input participation
! I <= V x O and output participation Q <= O x V are restricted and
! projected out of T_flow - Level 2's own projections - and the
! direct value dependency A = Q o I stands composed, four pairs
! never written down. A is then READ as a directed interpretation
! and walked: w reaches e only TRANSITIVELY, through yhat, never by
! adjacency. The trainable dependency
!
!      J_Theta <= Y x Theta        { (r, w) }
!
! is GENERATED by scanning Theta against reachability to the row's
! home - and the home is read from L, never named in the
! derivation. The reverse structure is the transpose VIEW of the
! same J_Theta: one dependency description, forward and reverse, no
! second stored pattern, no backprop graph. This is a structural
! Jacobian PATTERN: no derivative value, no chain rule evaluated,
! no gradient, no 2, no 6, no 0 anywhere - dependency structure
! belongs to the MODEL, not to one data instance.
!
! Author: Komahan Boopathy (komahan@gatech.edu)
!=====================================================================!

program learning_level_6

  use learning_assert, only : report, verdict
  use learning_assert, only : SLOT_W, SLOT_X, SLOT_YHAT, SLOT_Y, SLOT_E
  use learning_assert, only : OP_PREDICT, OP_ERROR
  use learning_assert, only : PORT_IN1, PORT_IN2, PORT_OUT
  use graph_fractal        , only : set_graph => graph
  use map_set_representation, only : counted_set_representation, &
       & listed_set_representation
  use map_set        , only : set_map
  use map_inclusion  , only : inclusion_map, declared_subobject
  use relation_finitary , only : stored_relation, relation
  use relation_algebra, only : restrict_slot, project_slots, &
       &                             compose_binary
  use relation_binary , only : csr_relation, transposed_view, &
       &                             transpose_of
  use relation_algorithms, only : reachable
  use graph_fractal        , only : graph, known_branch, null_branch
  use view_relational, only : relational_binding, &
       & num_member_sets, member_set_at, num_relations, relation_at, &
       & holds_set

  implicit none


  ! Residual rows exist only from this level upward.
  integer, parameter :: ROW_R = 1

  type(set_graph)              :: v, o, p, y
  type(set_graph)               :: theta, p_in, p_out
  type(stored_relation)          :: flow, backwards, located
  type(stored_relation)          :: consumes, produces
  type(csr_relation)             :: a, a2
  type(csr_relation), target     :: j_theta, j_theta2
  type(transposed_view)          :: jt
  type(graph)             , target :: g
  type(graph)             , target :: scell(1), selem(1)
  type(graph)             , target :: rcell(1), relem(1)
  type(relational_binding)         :: bnd
  integer                          :: kcell
  type(graph)             , target :: g2
  type(graph)             , target :: scell2(1), selem2(1)
  type(graph)             , target :: rcell2(1), relem2(1)
  type(relational_binding)         :: bnd2
  integer                          :: kcell2
  integer                        :: table(3, 6)
  integer                        :: nfail
  type(set_map)     :: sets
  type(inclusion_map)     :: inclusions

  nfail = 0

  write(*,'(1x,a)') "============================================="
  write(*,'(1x,a)') "learning tower . level 6 . discretization"
  write(*,'(1x,a)') "============================================="

  call v % declare()
  call sets % bind(v, counted_set_representation(5))
  call o % declare()
  call sets % bind(o, counted_set_representation(2))
  call p % declare()
  call sets % bind(p, counted_set_representation(3))
  call y % declare()
  call sets % bind(y, counted_set_representation(1))
  call theta % declare()
  call sets       % bind(theta, listed_set_representation([SLOT_W]))
  call inclusions % include_in(theta, v)

  table(:, 1) = [OP_PREDICT, SLOT_W   , PORT_IN1]
  table(:, 2) = [OP_PREDICT, SLOT_X   , PORT_IN2]
  table(:, 3) = [OP_PREDICT, SLOT_YHAT, PORT_OUT]
  table(:, 4) = [OP_ERROR  , SLOT_YHAT, PORT_IN1]
  table(:, 5) = [OP_ERROR  , SLOT_Y   , PORT_IN2]
  table(:, 6) = [OP_ERROR  , SLOT_E   , PORT_OUT]
  flow = stored_relation('flow', [o, v, p], table, sets)

  ! THE one new level-6 fact: where the residual row is located.
  located = stored_relation('located', [y, v], &
       & reshape([ROW_R, SLOT_E], [2, 1]), sets)

  call p_in % declare()
  call sets       % bind(p_in, listed_set_representation([PORT_IN1, PORT_IN2]))
  call inclusions % include_in(p_in, p)
  call p_out % declare()
  call sets       % bind(p_out, listed_set_representation([PORT_OUT]))
  call inclusions % include_in(p_out, p)

  a = derive_direct(flow)
  ! 'value dependency': (S, P) as one sequence on each branch.
  call g % declare()
  do kcell = 1, 1
     call scell(kcell) % declare()
     call selem(kcell) % declare()
  end do
  do kcell = 1, 1
     call rcell(kcell) % declare()
     call relem(kcell) % declare()
  end do

  call bnd % bind_set(selem(1), v)
  call bnd % bind_relation(relem(1), a)

  do kcell = 1, 1
     scell(kcell) % branch(1) = known_branch(selem(kcell))
     if (kcell .lt. 1) scell(kcell) % branch(2) = &
          & known_branch(scell(kcell + 1))
  end do
  do kcell = 1, 1
     rcell(kcell) % branch(1) = known_branch(relem(kcell))
     if (kcell .lt. 1) rcell(kcell) % branch(2) = &
          & known_branch(rcell(kcell + 1))
  end do

  g % branch(1) = known_branch(scell(1))
  g % branch(2) = known_branch(rcell(1))

  j_theta = derive_trainable(a)

  call check_participation(nfail)
  call check_direct_dependency(nfail)
  call check_paths(nfail)
  call check_residual_home(nfail)
  call check_trainable_dependency(nfail)
  call check_trainable_support(nfail)
  call check_reverse_is_the_view(nfail)
  call check_order_invariance(nfail)

  call verdict(nfail, "level 6")

contains

  !===================================================================!
  ! The direct value dependency, algebra end to end: I who-consumes,
  ! Q who-produces, A = Q o I. These are Level 2's own projections,
  ! composed in the other order: there they gave the operation
  ! dependency O x O; here they give value dependency V x V.
  !===================================================================!

  function derive_direct(t_flow) result(dep)

    type(stored_relation), intent(in) :: t_flow
    type(csr_relation)                :: dep

    type(stored_relation) :: cons, prod

    cons = project_slots(restrict_slot(t_flow, 3, p_in , sets, inclusions), [2, 1], sets)
    prod = project_slots(restrict_slot(t_flow, 3, p_out, sets, inclusions), [1, 2], sets)
    dep  = compose_binary(cons, prod, sets)

    ! keep the participations visible for their own checks
    consumes = cons
    produces = prod

  end function derive_direct

  !===================================================================!
  ! The row's home, read FROM L by scanning V in declaration order -
  ! exactly one, or the level stops. SLOT_E appears nowhere here:
  ! the source of truth is the location relation.
  !===================================================================!

  integer function home_of(row) result(home)

    integer, intent(in) :: row

    integer :: jv, hits

    hits = 0
    home = 0
    do jv = 1, sets % size_of(v)
       if (located % has([row, sets % member_of(v, jv)])) then
          hits = hits + 1
          home = sets % member_of(v, jv)
       end if
    end do
    if (hits .ne. 1) then
       error stop 'level 6: a residual row lives at exactly one value slot'
    end if

  end function home_of

  !===================================================================!
  ! The trainable dependency, generated - never written: (row, theta)
  ! enters IFF theta reaches the row's home through the interpreted
  ! value dependency. The pair (r, w) may appear in assertions only.
  !===================================================================!

  function derive_trainable(dep_view) result(jth)

    type(csr_relation), intent(in) :: dep_view
    type(csr_relation)                        :: jth

    integer, allocatable :: pairs(:,:)
    integer :: npairs, ri, ti, row

    allocate(pairs(2, sets % size_of(y) * sets % size_of(theta)))

    npairs = 0
    do ri = 1, sets % size_of(y)
       row = sets % member_of(y, ri)
       do ti = 1, sets % size_of(theta)
          if (reachable(dep_view, sets, sets % member_of(theta, ti), home_of(row))) then
             npairs = npairs + 1
             pairs(:, npairs) = [row, sets % member_of(theta, ti)]
          end if
       end do
    end do

    jth = csr_relation('trainable dependency', y, theta, &
         & pairs(:, 1:npairs), sets)

  end function derive_trainable

  !===================================================================!
  ! Input and output participation, exact - restricted and projected
  ! out of the flow, nothing hand-written.
  !===================================================================!

  subroutine check_participation(nfail)

    integer, intent(inout) :: nfail

    type(set_graph) :: dom

    dom = consumes % domain(1)
    call report(dom % same_as(v), "I runs from the value slots", nfail)
    dom = consumes % domain(2)
    call report(dom % same_as(o), "into the operations", nfail)
    call report(consumes % num_tuples() .eq. 4 .and. &
         &      consumes % has([SLOT_W   , OP_PREDICT]) .and. &
         &      consumes % has([SLOT_X   , OP_PREDICT]) .and. &
         &      consumes % has([SLOT_YHAT, OP_ERROR  ]) .and. &
         &      consumes % has([SLOT_Y   , OP_ERROR  ]), &
         & "I = { (w,predict), (x,predict), (yhat,error), " // &
         & "(y,error) } - exactly", nfail)

    dom = produces % domain(1)
    call report(dom % same_as(o), "Q runs from the operations", nfail)
    dom = produces % domain(2)
    call report(dom % same_as(v), "back into the value slots", nfail)
    call report(produces % num_tuples() .eq. 2 .and. &
         &      produces % has([OP_PREDICT, SLOT_YHAT]) .and. &
         &      produces % has([OP_ERROR  , SLOT_E   ]), &
         & "Q = { (predict,yhat), (error,e) } - exactly", nfail)

  end subroutine check_participation

  !===================================================================!
  ! The composed dependency: four direct pairs, and the absences
  ! that make transitivity mean something.
  !===================================================================!

  subroutine check_direct_dependency(nfail)

    integer, intent(inout) :: nfail

    type(set_graph) :: dom

    dom = a % domain(1)
    call report(dom % same_as(v), "A runs from the value slots", nfail)
    dom = a % domain(2)
    call report(dom % same_as(v), "back into the value slots", nfail)

    call report(a % num_tuples() .eq. 4 .and. &
         &      a % has([SLOT_W   , SLOT_YHAT]) .and. &
         &      a % has([SLOT_X   , SLOT_YHAT]) .and. &
         &      a % has([SLOT_YHAT, SLOT_E   ]) .and. &
         &      a % has([SLOT_Y   , SLOT_E   ]), &
         & "A = { (w,yhat), (x,yhat), (yhat,e), (y,e) } - exactly", &
         & nfail)
    call report(.not. a % has([SLOT_W, SLOT_E]) .and. &
         &      .not. a % has([SLOT_E, SLOT_W]), &
         & "w touches e in neither direction: influence is not " // &
         & "adjacency", nfail)

  end subroutine check_direct_dependency

  !===================================================================!
  ! The structural paths: every slot that feeds the model reaches e;
  ! nothing flows back; and w's influence on e is TRANSITIVE -
  ! through yhat - never direct, never hard-coded.
  !===================================================================!

  subroutine check_paths(nfail)

    integer, intent(inout) :: nfail

    type(set_graph) :: dom

    dom = a % source()
    call report(dom % same_as(v), &
         & "the interpretation walks the value slots", nfail)

    call report(reachable(a, sets, SLOT_W   , SLOT_E) .and. &
         &      reachable(a, sets, SLOT_X   , SLOT_E) .and. &
         &      reachable(a, sets, SLOT_YHAT, SLOT_E) .and. &
         &      reachable(a, sets, SLOT_Y   , SLOT_E), &
         & "w, x, yhat and y all reach e", nfail)
    call report(.not. reachable(a, sets, SLOT_E, SLOT_W), &
         & "reachable(e, sets, w) = false: nothing flows back", nfail)

    call report(a % has([SLOT_W, SLOT_YHAT]) .and. &
         &      a % has([SLOT_YHAT, SLOT_E]) .and. &
         &      .not. a % has([SLOT_W, SLOT_E]) .and. &
         &      reachable(a, sets, SLOT_W, SLOT_E), &
         & "w -> yhat -> e: adjacent twice, transitive once, " // &
         & "hard-coded never", nfail)

  end subroutine check_paths

  !===================================================================!
  ! The location relation holds one fact, and the derivation reads
  ! it back by scanning V against L. Only the assertion names e.
  !===================================================================!

  subroutine check_residual_home(nfail)

    integer, intent(inout) :: nfail

    call report(located % num_tuples() .eq. 1 .and. &
         &      located % has([ROW_R, SLOT_E]), &
         & "L = { (r, e) }: the one architect-owned fact", nfail)
    call report(home_of(ROW_R) .eq. SLOT_E, &
         & "the row's home is read from L - and it is e", nfail)

  end subroutine check_residual_home

  !===================================================================!
  ! J_Theta, exact: |Y| = |Theta| = 1, so one membership proves the
  ! complete extension. The pair is named HERE, in the assertion -
  ! never in the construction path.
  !===================================================================!

  subroutine check_trainable_dependency(nfail)

    integer, intent(inout) :: nfail

    type(set_graph) :: dom

    dom = j_theta % domain(1)
    call report(dom % same_as(y), &
         & "J_Theta runs from the residual rows", nfail)
    dom = j_theta % domain(2)
    call report(dom % same_as(theta), &
         & "into the trainable domain", nfail)

    call report(j_theta % num_tuples() .eq. 1, &
         & "|J_Theta| = 1", nfail)
    call report(j_theta % has([ROW_R, SLOT_W]), &
         & "J_Theta = { (r, w) }: w structurally influences r", nfail)

  end subroutine check_trainable_dependency

  !===================================================================!
  ! The trainable support of the residual, composed locally from
  ! membership by scanning Theta - no support_of_row() exists in
  ! production, none is needed.
  !===================================================================!

  subroutine check_trainable_support(nfail)

    integer, intent(inout) :: nfail

    type(set_graph) :: sr
    integer          :: ti, n
    integer, allocatable          :: kept(:)

    allocate(kept(sets % size_of(theta)))
    n = 0
    do ti = 1, sets % size_of(theta)
       if (j_theta % has([ROW_R, sets % member_of(theta, ti)])) then
          n = n + 1
          kept(n) = sets % member_of(theta, ti)
       end if
    end do
    call sr % declare()
    call sets       % bind(sr, listed_set_representation(kept(1:n)))
    call inclusions % include_in(sr, theta)

    call report(sets % size_of(sr) .eq. 1 .and. sets % has_in(sr, SLOT_W), &
         & "support(r) = { w }, composed, not stored", nfail)
    call report(declared_subobject(sr, theta, inclusions), &
         & "and it stands embedded in the trainable domain", nfail)

  end subroutine check_trainable_support

  !===================================================================!
  ! One dependency description: the reverse structure is the
  ! transpose VIEW of J_Theta - (w, r), borrowed, never a second
  ! stored pattern, never a backprop graph.
  !===================================================================!

  subroutine check_reverse_is_the_view(nfail)

    integer, intent(inout) :: nfail

    jt = transpose_of(j_theta)

    call report(jt % num_tuples() .eq. 1 .and. &
         &      jt % has([SLOT_W, ROW_R]), &
         & "J_Theta^T = { (w, r) }: the same truth, ends swapped", &
         & nfail)
    call report(j_theta % materialized() .and. &
         &      .not. jt % materialized(), &
         & "the forward is materialized; the reverse merely borrows", &
         & nfail)

  end subroutine check_reverse_is_the_view

  !===================================================================!
  ! The six facts handed backwards derive the same A and the same
  ! J_Theta - equal as sets, both directions: the dependency belongs
  ! to the model, not to how its table was typed.
  !===================================================================!

  subroutine check_order_invariance(nfail)

    integer, intent(inout) :: nfail

    integer              :: rev(3, 6), k
    integer, allocatable :: t1(:,:), t2(:,:)
    logical              :: ok

    do k = 1, 6
       rev(:, k) = table(:, 7 - k)
    end do
    backwards = stored_relation('flow backwards', [o, v, p], rev, sets)

    a2 = derive_direct(backwards)
    ! 'value dependency again': (S, P) as one sequence on each branch.
    call g2 % declare()
    do kcell2 = 1, 1
       call scell2(kcell2) % declare()
       call selem2(kcell2) % declare()
    end do
    do kcell2 = 1, 1
       call rcell2(kcell2) % declare()
       call relem2(kcell2) % declare()
    end do

    call bnd2 % bind_set(selem2(1), v)
    call bnd2 % bind_relation(relem2(1), a2)

    do kcell2 = 1, 1
       scell2(kcell2) % branch(1) = known_branch(selem2(kcell2))
       if (kcell2 .lt. 1) scell2(kcell2) % branch(2) = &
            & known_branch(scell2(kcell2 + 1))
    end do
    do kcell2 = 1, 1
       rcell2(kcell2) % branch(1) = known_branch(relem2(kcell2))
       if (kcell2 .lt. 1) rcell2(kcell2) % branch(2) = &
            & known_branch(rcell2(kcell2 + 1))
    end do

    g2 % branch(1) = known_branch(scell2(1))
    g2 % branch(2) = known_branch(rcell2(1))
    j_theta2 = derive_trainable(a2)

    call report(a2 % num_tuples() .eq. a % num_tuples(), &
         & "|A1| = |A2|", nfail)
    call a % tuples(t1)
    call a2 % tuples(t2)
    ok = .true.
    do k = 1, size(t1, 2)
       ok = ok .and. a2 % has(t1(:, k))
    end do
    do k = 1, size(t2, 2)
       ok = ok .and. a % has(t2(:, k))
    end do
    call report(ok, &
         & "each A holds every pair of the other: equal as sets", &
         & nfail)

    call report(j_theta2 % num_tuples() .eq. j_theta % num_tuples(), &
         & "|J1| = |J2|", nfail)
    call j_theta % tuples(t1)
    call j_theta2 % tuples(t2)
    ok = .true.
    do k = 1, size(t1, 2)
       ok = ok .and. j_theta2 % has(t1(:, k))
    end do
    do k = 1, size(t2, 2)
       ok = ok .and. j_theta % has(t2(:, k))
    end do
    call report(ok, &
         & "and so are the trainable dependencies, both directions", &
         & nfail)

  end subroutine check_order_invariance

end program learning_level_6
