!=====================================================================!
! LEARNING TOWER . LEVEL 6 . DISCRETIZATION
!
! The level answers one question: WHICH TRAINABLE PARAMETERS CAN
! STRUCTURALLY INFLUENCE EACH TRAINING RESIDUAL. One genuinely new
! fact enters - the LOCATION relation,
!
!      L <= Y x V        L = { (r, e) }
!
! where Y = { r } is the residual row, born at this level and
! nowhere below. EVERYTHING ELSE IS DERIVED: input participation
! I <= V x O and output participation Q <= O x V are restricted and
! projected out of R_flow - Level 2's own projections - and the
! direct value dependency A = Q o I stands composed, four pairs
! never written down. A is then READ as a directed interpretation
! and walked: w reaches e only TRANSITIVELY, through yhat, never by
! adjacency. The trainable dependency
!
!      J_Theta <= Y x Theta        { (r, w) }
!
! is GENERATED by scanning Theta against reachability to the row's
! home - and the home is read from L, never named in the
! derivation. The reverse structure is the transpose VIEW of the
! same J_Theta: one dependency description, forward and reverse, no
! second stored pattern, no backprop graph. This is a structural
! Jacobian PATTERN: no derivative value, no chain rule evaluated,
! no gradient, no 2, no 6, no 0 anywhere - dependency structure
! belongs to the MODEL, not to one data instance.
!
! Author: Komahan Boopathy (komahan@gatech.edu)
!=====================================================================!

program learning_level_6

  use learning_assert, only : report, verdict
  use learning_assert, only : SLOT_W, SLOT_X, SLOT_YHAT, SLOT_Y, SLOT_E
  use learning_assert, only : OP_PREDICT, OP_ERROR
  use learning_assert, only : PORT_IN1, PORT_IN2, PORT_OUT
  use graph_carrier  , only : counted_set, subset_set, member_set
  use graph_relation , only : stored_relation, relation
  use graph_relation_algebra, only : restrict_slot, project_slots, &
       &                             compose_binary
  use graph_binary_relation , only : csr_relation, transposed_view, &
       &                             transpose_of
  use graph_structure, only : relational_graph, held_set, held_relation
  use graph_profile  , only : directed_adjacency_view
  use graph_algorithms, only : reachable

  implicit none

  ! Residual rows exist only from this level upward.
  integer, parameter :: ROW_R = 1

  type(counted_set)              :: v, o, p, y
  type(subset_set)               :: theta, p_in, p_out
  type(stored_relation)          :: flow, backwards, located
  type(stored_relation)          :: consumes, produces
  type(csr_relation)             :: a, a2
  type(csr_relation), target     :: j_theta, j_theta2
  type(transposed_view)          :: jt
  type(relational_graph), target :: g, g2
  type(directed_adjacency_view)  :: view, view2
  integer                        :: table(3, 6)
  integer                        :: nfail

  nfail = 0

  write(*,'(1x,a)') "============================================="
  write(*,'(1x,a)') "learning tower . level 6 . discretization"
  write(*,'(1x,a)') "============================================="

  v     = counted_set('value-slots'  , 5)
  o     = counted_set('operations'   , 2)
  p     = counted_set('ports'        , 3)
  y     = counted_set('residual-rows', 1)
  theta = subset_set('trainable', v, [SLOT_W])

  table(:, 1) = [OP_PREDICT, SLOT_W   , PORT_IN1]
  table(:, 2) = [OP_PREDICT, SLOT_X   , PORT_IN2]
  table(:, 3) = [OP_PREDICT, SLOT_YHAT, PORT_OUT]
  table(:, 4) = [OP_ERROR  , SLOT_YHAT, PORT_IN1]
  table(:, 5) = [OP_ERROR  , SLOT_Y   , PORT_IN2]
  table(:, 6) = [OP_ERROR  , SLOT_E   , PORT_OUT]
  flow = stored_relation('flow', [o, v, p], table)

  ! THE one new level-6 fact: where the residual row is located.
  located = stored_relation('located', [y, v], &
       & reshape([ROW_R, SLOT_E], [2, 1]))

  p_in  = subset_set('input-ports', p, [PORT_IN1, PORT_IN2])
  p_out = subset_set('output-port', p, [PORT_OUT])

  a = derive_direct(flow)
  g = relational_graph('value dependency', [held_set(v)], &
       & [held_relation(a)])
  view = directed_adjacency_view(g, a)

  j_theta = derive_trainable(view)

  call check_participation(nfail)
  call check_direct_dependency(nfail)
  call check_paths(nfail)
  call check_residual_home(nfail)
  call check_trainable_dependency(nfail)
  call check_trainable_support(nfail)
  call check_reverse_is_the_view(nfail)
  call check_order_invariance(nfail)

  call verdict(nfail, "level 6")

contains

  !===================================================================!
  ! The direct value dependency, algebra end to end: I who-consumes,
  ! Q who-produces, A = Q o I. These are Level 2's own projections,
  ! composed in the other order: there they gave the operation
  ! dependency O x O; here they give value dependency V x V.
  !===================================================================!

  function derive_direct(r_flow) result(dep)

    type(stored_relation), intent(in) :: r_flow
    type(csr_relation)                :: dep

    type(stored_relation) :: cons, prod

    cons = project_slots(restrict_slot(r_flow, 3, p_in ), [2, 1])
    prod = project_slots(restrict_slot(r_flow, 3, p_out), [1, 2])
    dep  = compose_binary(cons, prod)

    ! keep the participations visible for their own checks
    consumes = cons
    produces = prod

  end function derive_direct

  !===================================================================!
  ! The row's home, read FROM L by scanning V in declaration order -
  ! exactly one, or the level stops. SLOT_E appears nowhere here:
  ! the source of truth is the location relation.
  !===================================================================!

  integer function home_of(row) result(home)

    integer, intent(in) :: row

    integer :: jv, hits

    hits = 0
    home = 0
    do jv = 1, v % size()
       if (located % has([row, v % member(jv)])) then
          hits = hits + 1
          home = v % member(jv)
       end if
    end do
    if (hits .ne. 1) then
       error stop 'level 6: a residual row lives at exactly one value slot'
    end if

  end function home_of

  !===================================================================!
  ! The trainable dependency, generated - never written: (row, theta)
  ! enters IFF theta reaches the row's home through the interpreted
  ! value dependency. The pair (r, w) may appear in assertions only.
  !===================================================================!

  function derive_trainable(dep_view) result(jth)

    type(directed_adjacency_view), intent(in) :: dep_view
    type(csr_relation)                        :: jth

    integer :: pairs(2, y % size() * theta % size())
    integer :: npairs, ri, ti, row

    npairs = 0
    do ri = 1, y % size()
       row = y % member(ri)
       do ti = 1, theta % size()
          if (reachable(dep_view, theta % member(ti), home_of(row))) then
             npairs = npairs + 1
             pairs(:, npairs) = [row, theta % member(ti)]
          end if
       end do
    end do

    jth = csr_relation('trainable dependency', y, theta, &
         & pairs(:, 1:npairs))

  end function derive_trainable

  !===================================================================!
  ! Input and output participation, exact - restricted and projected
  ! out of the flow, nothing hand-written.
  !===================================================================!

  subroutine check_participation(nfail)

    integer, intent(inout) :: nfail

    class(member_set), allocatable :: dom

    dom = consumes % domain(1)
    call report(dom % same_as(v), "I runs from the value slots", nfail)
    dom = consumes % domain(2)
    call report(dom % same_as(o), "into the operations", nfail)
    call report(consumes % num_tuples() .eq. 4 .and. &
         &      consumes % has([SLOT_W   , OP_PREDICT]) .and. &
         &      consumes % has([SLOT_X   , OP_PREDICT]) .and. &
         &      consumes % has([SLOT_YHAT, OP_ERROR  ]) .and. &
         &      consumes % has([SLOT_Y   , OP_ERROR  ]), &
         & "I = { (w,predict), (x,predict), (yhat,error), " // &
         & "(y,error) } - exactly", nfail)

    dom = produces % domain(1)
    call report(dom % same_as(o), "Q runs from the operations", nfail)
    dom = produces % domain(2)
    call report(dom % same_as(v), "back into the value slots", nfail)
    call report(produces % num_tuples() .eq. 2 .and. &
         &      produces % has([OP_PREDICT, SLOT_YHAT]) .and. &
         &      produces % has([OP_ERROR  , SLOT_E   ]), &
         & "Q = { (predict,yhat), (error,e) } - exactly", nfail)

  end subroutine check_participation

  !===================================================================!
  ! The composed dependency: four direct pairs, and the absences
  ! that make transitivity mean something.
  !===================================================================!

  subroutine check_direct_dependency(nfail)

    integer, intent(inout) :: nfail

    class(member_set), allocatable :: dom

    dom = a % domain(1)
    call report(dom % same_as(v), "A runs from the value slots", nfail)
    dom = a % domain(2)
    call report(dom % same_as(v), "back into the value slots", nfail)

    call report(a % num_tuples() .eq. 4 .and. &
         &      a % has([SLOT_W   , SLOT_YHAT]) .and. &
         &      a % has([SLOT_X   , SLOT_YHAT]) .and. &
         &      a % has([SLOT_YHAT, SLOT_E   ]) .and. &
         &      a % has([SLOT_Y   , SLOT_E   ]), &
         & "A = { (w,yhat), (x,yhat), (yhat,e), (y,e) } - exactly", &
         & nfail)
    call report(.not. a % has([SLOT_W, SLOT_E]) .and. &
         &      .not. a % has([SLOT_E, SLOT_W]), &
         & "w touches e in neither direction: influence is not " // &
         & "adjacency", nfail)

  end subroutine check_direct_dependency

  !===================================================================!
  ! The structural paths: every slot that feeds the model reaches e;
  ! nothing flows back; and w's influence on e is TRANSITIVE -
  ! through yhat - never direct, never hard-coded.
  !===================================================================!

  subroutine check_paths(nfail)

    integer, intent(inout) :: nfail

    class(member_set), allocatable :: dom

    dom = view % domain()
    call report(dom % same_as(v), &
         & "the interpretation walks the value slots", nfail)

    call report(reachable(view, SLOT_W   , SLOT_E) .and. &
         &      reachable(view, SLOT_X   , SLOT_E) .and. &
         &      reachable(view, SLOT_YHAT, SLOT_E) .and. &
         &      reachable(view, SLOT_Y   , SLOT_E), &
         & "w, x, yhat and y all reach e", nfail)
    call report(.not. reachable(view, SLOT_E, SLOT_W), &
         & "reachable(e, w) = false: nothing flows back", nfail)

    call report(a % has([SLOT_W, SLOT_YHAT]) .and. &
         &      a % has([SLOT_YHAT, SLOT_E]) .and. &
         &      .not. a % has([SLOT_W, SLOT_E]) .and. &
         &      reachable(view, SLOT_W, SLOT_E), &
         & "w -> yhat -> e: adjacent twice, transitive once, " // &
         & "hard-coded never", nfail)

  end subroutine check_paths

  !===================================================================!
  ! The location relation holds one fact, and the derivation reads
  ! it back by scanning V against L. Only the assertion names e.
  !===================================================================!

  subroutine check_residual_home(nfail)

    integer, intent(inout) :: nfail

    call report(located % num_tuples() .eq. 1 .and. &
         &      located % has([ROW_R, SLOT_E]), &
         & "L = { (r, e) }: the one architect-owned fact", nfail)
    call report(home_of(ROW_R) .eq. SLOT_E, &
         & "the row's home is read from L - and it is e", nfail)

  end subroutine check_residual_home

  !===================================================================!
  ! J_Theta, exact: |Y| = |Theta| = 1, so one membership proves the
  ! complete extension. The pair is named HERE, in the assertion -
  ! never in the construction path.
  !===================================================================!

  subroutine check_trainable_dependency(nfail)

    integer, intent(inout) :: nfail

    class(member_set), allocatable :: dom

    dom = j_theta % domain(1)
    call report(dom % same_as(y), &
         & "J_Theta runs from the residual rows", nfail)
    dom = j_theta % domain(2)
    call report(dom % same_as(theta), &
         & "into the trainable domain", nfail)

    call report(j_theta % num_tuples() .eq. 1, &
         & "|J_Theta| = 1", nfail)
    call report(j_theta % has([ROW_R, SLOT_W]), &
         & "J_Theta = { (r, w) }: w structurally influences r", nfail)

  end subroutine check_trainable_dependency

  !===================================================================!
  ! The trainable support of the residual, composed locally from
  ! membership by scanning Theta - no support_of_row() exists in
  ! production, none is needed.
  !===================================================================!

  subroutine check_trainable_support(nfail)

    integer, intent(inout) :: nfail

    type(subset_set) :: sr
    integer          :: ti, n
    integer          :: kept(theta % size())

    n = 0
    do ti = 1, theta % size()
       if (j_theta % has([ROW_R, theta % member(ti)])) then
          n = n + 1
          kept(n) = theta % member(ti)
       end if
    end do
    sr = subset_set('trainable support of r', theta, kept(1:n))

    call report(sr % size() .eq. 1 .and. sr % has(SLOT_W), &
         & "support(r) = { w }, composed, not stored", nfail)
    call report(sr % is_subobject_of(theta), &
         & "and it stands embedded in the trainable domain", nfail)

  end subroutine check_trainable_support

  !===================================================================!
  ! One dependency description: the reverse structure is the
  ! transpose VIEW of J_Theta - (w, r), borrowed, never a second
  ! stored pattern, never a backprop graph.
  !===================================================================!

  subroutine check_reverse_is_the_view(nfail)

    integer, intent(inout) :: nfail

    jt = transpose_of(j_theta)

    call report(jt % num_tuples() .eq. 1 .and. &
         &      jt % has([SLOT_W, ROW_R]), &
         & "J_Theta^T = { (w, r) }: the same truth, ends swapped", &
         & nfail)
    call report(j_theta % materialized() .and. &
         &      .not. jt % materialized(), &
         & "the forward is materialized; the reverse merely borrows", &
         & nfail)

  end subroutine check_reverse_is_the_view

  !===================================================================!
  ! The six facts handed backwards derive the same A and the same
  ! J_Theta - equal as sets, both directions: the dependency belongs
  ! to the model, not to how its table was typed.
  !===================================================================!

  subroutine check_order_invariance(nfail)

    integer, intent(inout) :: nfail

    integer              :: rev(3, 6), k
    integer, allocatable :: t1(:,:), t2(:,:)
    logical              :: ok

    do k = 1, 6
       rev(:, k) = table(:, 7 - k)
    end do
    backwards = stored_relation('flow backwards', [o, v, p], rev)

    a2 = derive_direct(backwards)
    g2 = relational_graph('value dependency again', [held_set(v)], &
         & [held_relation(a2)])
    view2 = directed_adjacency_view(g2, a2)
    j_theta2 = derive_trainable(view2)

    call report(a2 % num_tuples() .eq. a % num_tuples(), &
         & "|A1| = |A2|", nfail)
    call a % tuples(t1)
    call a2 % tuples(t2)
    ok = .true.
    do k = 1, size(t1, 2)
       ok = ok .and. a2 % has(t1(:, k))
    end do
    do k = 1, size(t2, 2)
       ok = ok .and. a % has(t2(:, k))
    end do
    call report(ok, &
         & "each A holds every pair of the other: equal as sets", &
         & nfail)

    call report(j_theta2 % num_tuples() .eq. j_theta % num_tuples(), &
         & "|J1| = |J2|", nfail)
    call j_theta % tuples(t1)
    call j_theta2 % tuples(t2)
    ok = .true.
    do k = 1, size(t1, 2)
       ok = ok .and. j_theta2 % has(t1(:, k))
    end do
    do k = 1, size(t2, 2)
       ok = ok .and. j_theta % has(t2(:, k))
    end do
    call report(ok, &
         & "and so are the trainable dependencies, both directions", &
         & nfail)

  end subroutine check_order_invariance

end program learning_level_6
